sigprocmask:sigprocmask.c
	gcc $^ -o $@ 
compete:compete.c
	gcc $^ -o $@ 
signal5:signal5.c
	gcc $^ -o $@ 
signal4:signal4.c
	gcc $^ -o $@ -O2
signal3:signal3.c
	gcc $^ -o $@ -O2
.PHONY:clean
clean:
	rm -rf signal3
signal2:signal2.c
	gcc $^ -o $@
signal:signal.c
	gcc $^ -o $@
