fifo5:fifo5.c
	gcc $^ -o $@
fifo4:fifo4.c
	gcc $^ -o $@
fifo2:fifo2.c
	gcc $^ -o $@
fifo:fifo.c
	gcc $^ -o $@
pipe5:pipe5.c
	gcc $^ -o $@
pipe4:pipe4.c
	gcc $^ -o $@
pipe3:pipe3.c
	gcc $^ -o $@
pipe2:pipe2.c
	gcc $^ -o $@
pipe:pipe.c
	gcc $^ -o $@
